### ISSUE TITLE
Adopt parsebib or csl json, biblatex and bibtex support?

### ISSUE THREAD

**Issue by bdarcus** [andras-simonyi/citeproc-el#18] opened 2021-05-29 23:31 UTC
Am I correct citeproc-el doesn't currently support biblatex?

If not, might it be worthwhile to use parsebib, which will soon include direct file parsing and csl json support?

https://github.com/joostkremers/parsebib/issues/12

**Comment by denismaier** [comment] 2021-05-30 08:51
Duplicate of #1 ?

**Comment by bdarcus** [comment] 2021-05-30 10:42
I missed that, but it's not a pure duplicate.

If @andras-simonyi doesn't see any promise in the direction of that parsebib discussion, he can just close this as won't fix, and focus instead on #1.

But in any case, biblatex support would be great, particularly as I can't get json working ATM.

**Closed** 2021-05-30 11:00 UTC
