### ISSUE TITLE
When citing multiple articles and using a modifier, only the first article gets the modifier

### ISSUE THREAD

**Issue by mbosley** [andras-simonyi/citeproc-el#61] opened 2021-10-18 13:27 UTC
Hi there, thanks for your work on this package!

My expectation for a citation of the form: `[cite/t:@albertConstitutionalHandcuffs2010;@albertAmendingConstitutionalAmendment2015]` is this, which I get when I export using natbib's apalike.
![Screen Shot 2021-10-18 at 9 26 02 AM](https://user-images.githubusercontent.com/37943910/137740403-9c2ce83c-f77c-4f53-b364-69e16bafbb07.png)

However, when exporting with CSL using the citeproc engine, I get this:

![Screen Shot 2021-10-18 at 9 27 16 AM](https://user-images.githubusercontent.com/37943910/137740610-7969c8ae-2bcf-4309-8eb8-fa20e811800f.png)

**Comment by bdarcus** [comment] 2021-10-18 13:29
Is it possible the issue is the style?

CSL has rules for sorting of citations.

**Comment by mbosley** [comment] 2021-10-18 13:52
The disambiguation suffix is a minor concern, but the major concern is that using CSL, I get "Albert (Albert, 2015b, 2010)", which is not the intended output (w.r.t. the doubling up of the name). There should be no second "Albert" within the parentheses.

**Comment by bdarcus** [comment] 2021-10-18 13:56
Sorry for the noise; I obviously missed that!

So for some reason, the "text" style isn't working correctly there.

I've not seen that behavior myself.

**Comment by andras-simonyi** [comment] 2021-11-02 11:21
I've just merged a pull request which hopefully solves the problem. Could you check?

**Comment by mbosley** [comment] 2021-11-02 23:58
> I've just merged a pull request which hopefully solves the problem. Could you check?

Looks like it works now. Thanks for this!

**Closed** 2021-11-03 05:52 UTC
Labels: bug
